export const MODULE_NAME = "fast-flip";

export const LOCALIZATION = {
    MIRROR_HORIZONTAL_HOTKEY: `${MODULE_NAME}.mirror-horizontal-hotkey`,
    MIRROR_HORIZONTAL_HINT: `${MODULE_NAME}.mirror-horizontal-hint`,
    MIRROR_HORIZONTAL_BUTTON: `${MODULE_NAME}.mirror-horizontal-button`,
    MIRROR_VERTICAL_HOTKEY: `${MODULE_NAME}.mirror-vertical-hotkey`,
    MIRROR_VERTICAL_HINT: `${MODULE_NAME}.mirror-vertical-hint`,
    MIRROR_VERTICAL_BUTTON: `${MODULE_NAME}.mirror-vertical-button`,
    TOGGLE_AFK_HOTKEY: `${MODULE_NAME}.toggle-afk-hotkey`,
    TOGGLE_AFK_HINT: `${MODULE_NAME}.toggle-afk-hint`,
    TOGGLE_AFK_BUTTON: `${MODULE_NAME}.toggle-afk-button`,
    SHOW_MIRROR_BUTTONS: `${MODULE_NAME}.show-mirror-buttons`,
    SHOW_MIRROR_BUTTONS_HINT: `${MODULE_NAME}.show-mirror-buttons-hint`,
    SHOW_TOGGLE_AFK_BUTTON: `${MODULE_NAME}.show-toggle-afk-button`,
    SHOW_TOGGLE_AFK_HINT: `${MODULE_NAME}.show-toggle-afk-hint`,
    AFK_OVERLAY_ICON_PATH: `${MODULE_NAME}.afk-overlay-icon-path`,
    AFK_OVERLAY_ICON_PATH_HINT: `${MODULE_NAME}.afk-overlay-icon-path-hint`,
    ALLOW_AFK_TOGGLE: `${MODULE_NAME}.allow-afk-toggle`,
    ALLOW_AFK_TOGGLE_HINT: `${MODULE_NAME}.allow-afk-toggle-hint`,
    SHOW_AFK_STATUS_IN_CHAT: `${MODULE_NAME}.show-afk-status-in-chat`,
    SHOW_AFK_STATUS_IN_CHAT_HINT: `${MODULE_NAME}.show-afk-status-in-chat-hint`,
    CHAT_AFK_MESSAGE: `${MODULE_NAME}.chat-afk-message`,
    CHAT_RETURNED_MESSAGE: `${MODULE_NAME}.chat-returned-message`,
    SHOW_SPEECH_BUBBLE_HOTKEY: `${MODULE_NAME}.show-speech-bubble-hotkey`,
    SHOW_SPEECH_BUBBLE_HINT: `${MODULE_NAME}.show-speech-bubble-hint`,
    ALLOW_SPEECH_BUBBLES: `${MODULE_NAME}.allow-speech-bubbles`,
    ALLOW_SPEECH_BUBBLES_HINT: `${MODULE_NAME}.allow-speech-bubbles-hint`,
    SPEECH_BUBBLE_FONT_SIZE: `${MODULE_NAME}.speech-bubble-font-size`,
    SPEECH_BUBBLE_FONT_SIZE_HINT: `${MODULE_NAME}.speech-bubble-font-size-hint`,
    ANIMATION_DURATION: `${MODULE_NAME}.animation-duration`,
    ANIMATION_DURATION_HINT: `${MODULE_NAME}.animation-duration-hint`,
} as const;
